# Generated by Django 4.1.7 on 2023-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_last', models.CharField(max_length=100)),
                ('name_first', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
